/*
VulnCheck API

VulnCheck API (v3 + v4)

API version: latest
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination{}

// RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination render.ResponseWithMetadata-array_advisory_RhelCVE-paginate_Pagination
type RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination struct {
	Benchmark *float32 `json:"_benchmark,omitempty"`
	Meta *PaginatePagination `json:"_meta,omitempty"`
	Data []AdvisoryRhelCVE `json:"data,omitempty"`
}

// NewRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination instantiates a new RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination() *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination {
	this := RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination{}
	return &this
}

// NewRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePaginationWithDefaults instantiates a new RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePaginationWithDefaults() *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination {
	this := RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination{}
	return &this
}

// GetBenchmark returns the Benchmark field value if set, zero value otherwise.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) GetBenchmark() float32 {
	if o == nil || IsNil(o.Benchmark) {
		var ret float32
		return ret
	}
	return *o.Benchmark
}

// GetBenchmarkOk returns a tuple with the Benchmark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) GetBenchmarkOk() (*float32, bool) {
	if o == nil || IsNil(o.Benchmark) {
		return nil, false
	}
	return o.Benchmark, true
}

// HasBenchmark returns a boolean if a field has been set.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) HasBenchmark() bool {
	if o != nil && !IsNil(o.Benchmark) {
		return true
	}

	return false
}

// SetBenchmark gets a reference to the given float32 and assigns it to the Benchmark field.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) SetBenchmark(v float32) {
	o.Benchmark = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) GetMeta() PaginatePagination {
	if o == nil || IsNil(o.Meta) {
		var ret PaginatePagination
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) GetMetaOk() (*PaginatePagination, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginatePagination and assigns it to the Meta field.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) SetMeta(v PaginatePagination) {
	o.Meta = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) GetData() []AdvisoryRhelCVE {
	if o == nil || IsNil(o.Data) {
		var ret []AdvisoryRhelCVE
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) GetDataOk() ([]AdvisoryRhelCVE, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AdvisoryRhelCVE and assigns it to the Data field.
func (o *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) SetData(v []AdvisoryRhelCVE) {
	o.Data = v
}

func (o RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Benchmark) {
		toSerialize["_benchmark"] = o.Benchmark
	}
	if !IsNil(o.Meta) {
		toSerialize["_meta"] = o.Meta
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination struct {
	value *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination
	isSet bool
}

func (v NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) Get() *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination {
	return v.value
}

func (v *NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) Set(val *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination(val *RenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) *NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination {
	return &NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination{value: val, isSet: true}
}

func (v NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderResponseWithMetadataArrayAdvisoryRhelCVEPaginatePagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


