/*
VulnCheck API

VulnCheck API (v3 + v4)

API version: latest
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the ApiTargetIntel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTargetIntel{}

// ApiTargetIntel api.TargetIntel
type ApiTargetIntel struct {
	AsDomain *string `json:"as_domain,omitempty"`
	AsName *string `json:"as_name,omitempty"`
	Asn *string `json:"asn,omitempty"`
	Classifications []string `json:"classifications,omitempty"`
	ContainsCve *bool `json:"contains_cve,omitempty"`
	Country *string `json:"country,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	Cpe []string `json:"cpe,omitempty"`
	Cve []string `json:"cve,omitempty"`
	DateAdded *string `json:"date_added,omitempty"`
	Fingerprints []ApiFingerprint `json:"fingerprints,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	Ip *string `json:"ip,omitempty"`
	Metadata []int32 `json:"metadata,omitempty"`
	Port *int32 `json:"port,omitempty"`
	Product []string `json:"product,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
	Vendor []string `json:"vendor,omitempty"`
	Version []string `json:"version,omitempty"`
}

// NewApiTargetIntel instantiates a new ApiTargetIntel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTargetIntel() *ApiTargetIntel {
	this := ApiTargetIntel{}
	return &this
}

// NewApiTargetIntelWithDefaults instantiates a new ApiTargetIntel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTargetIntelWithDefaults() *ApiTargetIntel {
	this := ApiTargetIntel{}
	return &this
}

// GetAsDomain returns the AsDomain field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetAsDomain() string {
	if o == nil || IsNil(o.AsDomain) {
		var ret string
		return ret
	}
	return *o.AsDomain
}

// GetAsDomainOk returns a tuple with the AsDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetAsDomainOk() (*string, bool) {
	if o == nil || IsNil(o.AsDomain) {
		return nil, false
	}
	return o.AsDomain, true
}

// HasAsDomain returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasAsDomain() bool {
	if o != nil && !IsNil(o.AsDomain) {
		return true
	}

	return false
}

// SetAsDomain gets a reference to the given string and assigns it to the AsDomain field.
func (o *ApiTargetIntel) SetAsDomain(v string) {
	o.AsDomain = &v
}

// GetAsName returns the AsName field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetAsName() string {
	if o == nil || IsNil(o.AsName) {
		var ret string
		return ret
	}
	return *o.AsName
}

// GetAsNameOk returns a tuple with the AsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetAsNameOk() (*string, bool) {
	if o == nil || IsNil(o.AsName) {
		return nil, false
	}
	return o.AsName, true
}

// HasAsName returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasAsName() bool {
	if o != nil && !IsNil(o.AsName) {
		return true
	}

	return false
}

// SetAsName gets a reference to the given string and assigns it to the AsName field.
func (o *ApiTargetIntel) SetAsName(v string) {
	o.AsName = &v
}

// GetAsn returns the Asn field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetAsn() string {
	if o == nil || IsNil(o.Asn) {
		var ret string
		return ret
	}
	return *o.Asn
}

// GetAsnOk returns a tuple with the Asn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetAsnOk() (*string, bool) {
	if o == nil || IsNil(o.Asn) {
		return nil, false
	}
	return o.Asn, true
}

// HasAsn returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasAsn() bool {
	if o != nil && !IsNil(o.Asn) {
		return true
	}

	return false
}

// SetAsn gets a reference to the given string and assigns it to the Asn field.
func (o *ApiTargetIntel) SetAsn(v string) {
	o.Asn = &v
}

// GetClassifications returns the Classifications field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetClassifications() []string {
	if o == nil || IsNil(o.Classifications) {
		var ret []string
		return ret
	}
	return o.Classifications
}

// GetClassificationsOk returns a tuple with the Classifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetClassificationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Classifications) {
		return nil, false
	}
	return o.Classifications, true
}

// HasClassifications returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasClassifications() bool {
	if o != nil && !IsNil(o.Classifications) {
		return true
	}

	return false
}

// SetClassifications gets a reference to the given []string and assigns it to the Classifications field.
func (o *ApiTargetIntel) SetClassifications(v []string) {
	o.Classifications = v
}

// GetContainsCve returns the ContainsCve field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetContainsCve() bool {
	if o == nil || IsNil(o.ContainsCve) {
		var ret bool
		return ret
	}
	return *o.ContainsCve
}

// GetContainsCveOk returns a tuple with the ContainsCve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetContainsCveOk() (*bool, bool) {
	if o == nil || IsNil(o.ContainsCve) {
		return nil, false
	}
	return o.ContainsCve, true
}

// HasContainsCve returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasContainsCve() bool {
	if o != nil && !IsNil(o.ContainsCve) {
		return true
	}

	return false
}

// SetContainsCve gets a reference to the given bool and assigns it to the ContainsCve field.
func (o *ApiTargetIntel) SetContainsCve(v bool) {
	o.ContainsCve = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *ApiTargetIntel) SetCountry(v string) {
	o.Country = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *ApiTargetIntel) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetCpe returns the Cpe field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetCpe() []string {
	if o == nil || IsNil(o.Cpe) {
		var ret []string
		return ret
	}
	return o.Cpe
}

// GetCpeOk returns a tuple with the Cpe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetCpeOk() ([]string, bool) {
	if o == nil || IsNil(o.Cpe) {
		return nil, false
	}
	return o.Cpe, true
}

// HasCpe returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasCpe() bool {
	if o != nil && !IsNil(o.Cpe) {
		return true
	}

	return false
}

// SetCpe gets a reference to the given []string and assigns it to the Cpe field.
func (o *ApiTargetIntel) SetCpe(v []string) {
	o.Cpe = v
}

// GetCve returns the Cve field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetCve() []string {
	if o == nil || IsNil(o.Cve) {
		var ret []string
		return ret
	}
	return o.Cve
}

// GetCveOk returns a tuple with the Cve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetCveOk() ([]string, bool) {
	if o == nil || IsNil(o.Cve) {
		return nil, false
	}
	return o.Cve, true
}

// HasCve returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasCve() bool {
	if o != nil && !IsNil(o.Cve) {
		return true
	}

	return false
}

// SetCve gets a reference to the given []string and assigns it to the Cve field.
func (o *ApiTargetIntel) SetCve(v []string) {
	o.Cve = v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *ApiTargetIntel) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetFingerprints returns the Fingerprints field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetFingerprints() []ApiFingerprint {
	if o == nil || IsNil(o.Fingerprints) {
		var ret []ApiFingerprint
		return ret
	}
	return o.Fingerprints
}

// GetFingerprintsOk returns a tuple with the Fingerprints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetFingerprintsOk() ([]ApiFingerprint, bool) {
	if o == nil || IsNil(o.Fingerprints) {
		return nil, false
	}
	return o.Fingerprints, true
}

// HasFingerprints returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasFingerprints() bool {
	if o != nil && !IsNil(o.Fingerprints) {
		return true
	}

	return false
}

// SetFingerprints gets a reference to the given []ApiFingerprint and assigns it to the Fingerprints field.
func (o *ApiTargetIntel) SetFingerprints(v []ApiFingerprint) {
	o.Fingerprints = v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *ApiTargetIntel) SetHostname(v string) {
	o.Hostname = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *ApiTargetIntel) SetIp(v string) {
	o.Ip = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetMetadata() []int32 {
	if o == nil || IsNil(o.Metadata) {
		var ret []int32
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetMetadataOk() ([]int32, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []int32 and assigns it to the Metadata field.
func (o *ApiTargetIntel) SetMetadata(v []int32) {
	o.Metadata = v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *ApiTargetIntel) SetPort(v int32) {
	o.Port = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetProduct() []string {
	if o == nil || IsNil(o.Product) {
		var ret []string
		return ret
	}
	return o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetProductOk() ([]string, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given []string and assigns it to the Product field.
func (o *ApiTargetIntel) SetProduct(v []string) {
	o.Product = v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *ApiTargetIntel) SetProtocol(v string) {
	o.Protocol = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *ApiTargetIntel) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetVendor() []string {
	if o == nil || IsNil(o.Vendor) {
		var ret []string
		return ret
	}
	return o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetVendorOk() ([]string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given []string and assigns it to the Vendor field.
func (o *ApiTargetIntel) SetVendor(v []string) {
	o.Vendor = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ApiTargetIntel) GetVersion() []string {
	if o == nil || IsNil(o.Version) {
		var ret []string
		return ret
	}
	return o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTargetIntel) GetVersionOk() ([]string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ApiTargetIntel) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given []string and assigns it to the Version field.
func (o *ApiTargetIntel) SetVersion(v []string) {
	o.Version = v
}

func (o ApiTargetIntel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTargetIntel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AsDomain) {
		toSerialize["as_domain"] = o.AsDomain
	}
	if !IsNil(o.AsName) {
		toSerialize["as_name"] = o.AsName
	}
	if !IsNil(o.Asn) {
		toSerialize["asn"] = o.Asn
	}
	if !IsNil(o.Classifications) {
		toSerialize["classifications"] = o.Classifications
	}
	if !IsNil(o.ContainsCve) {
		toSerialize["contains_cve"] = o.ContainsCve
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.Cpe) {
		toSerialize["cpe"] = o.Cpe
	}
	if !IsNil(o.Cve) {
		toSerialize["cve"] = o.Cve
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.Fingerprints) {
		toSerialize["fingerprints"] = o.Fingerprints
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableApiTargetIntel struct {
	value *ApiTargetIntel
	isSet bool
}

func (v NullableApiTargetIntel) Get() *ApiTargetIntel {
	return v.value
}

func (v *NullableApiTargetIntel) Set(val *ApiTargetIntel) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTargetIntel) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTargetIntel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTargetIntel(val *ApiTargetIntel) *NullableApiTargetIntel {
	return &NullableApiTargetIntel{value: val, isSet: true}
}

func (v NullableApiTargetIntel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTargetIntel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


