/*
VulnCheck API

VulnCheck API (v3 + v4)

API version: latest
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the SearchV4AdvisoryReturnValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchV4AdvisoryReturnValue{}

// SearchV4AdvisoryReturnValue search.V4AdvisoryReturnValue
type SearchV4AdvisoryReturnValue struct {
	Meta *SearchV4AdvisoryMeta `json:"_meta,omitempty"`
	Data []AdvisoryMitreCVEListV5Ref `json:"data,omitempty"`
}

// NewSearchV4AdvisoryReturnValue instantiates a new SearchV4AdvisoryReturnValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchV4AdvisoryReturnValue() *SearchV4AdvisoryReturnValue {
	this := SearchV4AdvisoryReturnValue{}
	return &this
}

// NewSearchV4AdvisoryReturnValueWithDefaults instantiates a new SearchV4AdvisoryReturnValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchV4AdvisoryReturnValueWithDefaults() *SearchV4AdvisoryReturnValue {
	this := SearchV4AdvisoryReturnValue{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SearchV4AdvisoryReturnValue) GetMeta() SearchV4AdvisoryMeta {
	if o == nil || IsNil(o.Meta) {
		var ret SearchV4AdvisoryMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchV4AdvisoryReturnValue) GetMetaOk() (*SearchV4AdvisoryMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SearchV4AdvisoryReturnValue) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given SearchV4AdvisoryMeta and assigns it to the Meta field.
func (o *SearchV4AdvisoryReturnValue) SetMeta(v SearchV4AdvisoryMeta) {
	o.Meta = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SearchV4AdvisoryReturnValue) GetData() []AdvisoryMitreCVEListV5Ref {
	if o == nil || IsNil(o.Data) {
		var ret []AdvisoryMitreCVEListV5Ref
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchV4AdvisoryReturnValue) GetDataOk() ([]AdvisoryMitreCVEListV5Ref, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SearchV4AdvisoryReturnValue) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AdvisoryMitreCVEListV5Ref and assigns it to the Data field.
func (o *SearchV4AdvisoryReturnValue) SetData(v []AdvisoryMitreCVEListV5Ref) {
	o.Data = v
}

func (o SearchV4AdvisoryReturnValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchV4AdvisoryReturnValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["_meta"] = o.Meta
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSearchV4AdvisoryReturnValue struct {
	value *SearchV4AdvisoryReturnValue
	isSet bool
}

func (v NullableSearchV4AdvisoryReturnValue) Get() *SearchV4AdvisoryReturnValue {
	return v.value
}

func (v *NullableSearchV4AdvisoryReturnValue) Set(val *SearchV4AdvisoryReturnValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchV4AdvisoryReturnValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchV4AdvisoryReturnValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchV4AdvisoryReturnValue(val *SearchV4AdvisoryReturnValue) *NullableSearchV4AdvisoryReturnValue {
	return &NullableSearchV4AdvisoryReturnValue{value: val, isSet: true}
}

func (v NullableSearchV4AdvisoryReturnValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchV4AdvisoryReturnValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


