/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the AdvisorySiemensSubSubBranch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvisorySiemensSubSubBranch{}

// AdvisorySiemensSubSubBranch struct for AdvisorySiemensSubSubBranch
type AdvisorySiemensSubSubBranch struct {
	Category *string `json:"category,omitempty"`
	Name *string `json:"name,omitempty"`
	Product *AdvisorySiemensProduct `json:"product,omitempty"`
}

// NewAdvisorySiemensSubSubBranch instantiates a new AdvisorySiemensSubSubBranch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvisorySiemensSubSubBranch() *AdvisorySiemensSubSubBranch {
	this := AdvisorySiemensSubSubBranch{}
	return &this
}

// NewAdvisorySiemensSubSubBranchWithDefaults instantiates a new AdvisorySiemensSubSubBranch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvisorySiemensSubSubBranchWithDefaults() *AdvisorySiemensSubSubBranch {
	this := AdvisorySiemensSubSubBranch{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *AdvisorySiemensSubSubBranch) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySiemensSubSubBranch) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *AdvisorySiemensSubSubBranch) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *AdvisorySiemensSubSubBranch) SetCategory(v string) {
	o.Category = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdvisorySiemensSubSubBranch) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySiemensSubSubBranch) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdvisorySiemensSubSubBranch) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdvisorySiemensSubSubBranch) SetName(v string) {
	o.Name = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *AdvisorySiemensSubSubBranch) GetProduct() AdvisorySiemensProduct {
	if o == nil || IsNil(o.Product) {
		var ret AdvisorySiemensProduct
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySiemensSubSubBranch) GetProductOk() (*AdvisorySiemensProduct, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *AdvisorySiemensSubSubBranch) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given AdvisorySiemensProduct and assigns it to the Product field.
func (o *AdvisorySiemensSubSubBranch) SetProduct(v AdvisorySiemensProduct) {
	o.Product = &v
}

func (o AdvisorySiemensSubSubBranch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvisorySiemensSubSubBranch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	return toSerialize, nil
}

type NullableAdvisorySiemensSubSubBranch struct {
	value *AdvisorySiemensSubSubBranch
	isSet bool
}

func (v NullableAdvisorySiemensSubSubBranch) Get() *AdvisorySiemensSubSubBranch {
	return v.value
}

func (v *NullableAdvisorySiemensSubSubBranch) Set(val *AdvisorySiemensSubSubBranch) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvisorySiemensSubSubBranch) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvisorySiemensSubSubBranch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvisorySiemensSubSubBranch(val *AdvisorySiemensSubSubBranch) *NullableAdvisorySiemensSubSubBranch {
	return &NullableAdvisorySiemensSubSubBranch{value: val, isSet: true}
}

func (v NullableAdvisorySiemensSubSubBranch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvisorySiemensSubSubBranch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


