/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the ApiMitreMitigation2D3fendMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMitreMitigation2D3fendMapping{}

// ApiMitreMitigation2D3fendMapping struct for ApiMitreMitigation2D3fendMapping
type ApiMitreMitigation2D3fendMapping struct {
	D3fendtechniques []ApiMitreD3fendTechnique `json:"d3fendtechniques,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewApiMitreMitigation2D3fendMapping instantiates a new ApiMitreMitigation2D3fendMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMitreMitigation2D3fendMapping() *ApiMitreMitigation2D3fendMapping {
	this := ApiMitreMitigation2D3fendMapping{}
	return &this
}

// NewApiMitreMitigation2D3fendMappingWithDefaults instantiates a new ApiMitreMitigation2D3fendMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMitreMitigation2D3fendMappingWithDefaults() *ApiMitreMitigation2D3fendMapping {
	this := ApiMitreMitigation2D3fendMapping{}
	return &this
}

// GetD3fendtechniques returns the D3fendtechniques field value if set, zero value otherwise.
func (o *ApiMitreMitigation2D3fendMapping) GetD3fendtechniques() []ApiMitreD3fendTechnique {
	if o == nil || IsNil(o.D3fendtechniques) {
		var ret []ApiMitreD3fendTechnique
		return ret
	}
	return o.D3fendtechniques
}

// GetD3fendtechniquesOk returns a tuple with the D3fendtechniques field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMitreMitigation2D3fendMapping) GetD3fendtechniquesOk() ([]ApiMitreD3fendTechnique, bool) {
	if o == nil || IsNil(o.D3fendtechniques) {
		return nil, false
	}
	return o.D3fendtechniques, true
}

// HasD3fendtechniques returns a boolean if a field has been set.
func (o *ApiMitreMitigation2D3fendMapping) HasD3fendtechniques() bool {
	if o != nil && !IsNil(o.D3fendtechniques) {
		return true
	}

	return false
}

// SetD3fendtechniques gets a reference to the given []ApiMitreD3fendTechnique and assigns it to the D3fendtechniques field.
func (o *ApiMitreMitigation2D3fendMapping) SetD3fendtechniques(v []ApiMitreD3fendTechnique) {
	o.D3fendtechniques = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiMitreMitigation2D3fendMapping) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMitreMitigation2D3fendMapping) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiMitreMitigation2D3fendMapping) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiMitreMitigation2D3fendMapping) SetId(v string) {
	o.Id = &v
}

func (o ApiMitreMitigation2D3fendMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMitreMitigation2D3fendMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.D3fendtechniques) {
		toSerialize["d3fendtechniques"] = o.D3fendtechniques
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableApiMitreMitigation2D3fendMapping struct {
	value *ApiMitreMitigation2D3fendMapping
	isSet bool
}

func (v NullableApiMitreMitigation2D3fendMapping) Get() *ApiMitreMitigation2D3fendMapping {
	return v.value
}

func (v *NullableApiMitreMitigation2D3fendMapping) Set(val *ApiMitreMitigation2D3fendMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMitreMitigation2D3fendMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMitreMitigation2D3fendMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMitreMitigation2D3fendMapping(val *ApiMitreMitigation2D3fendMapping) *NullableApiMitreMitigation2D3fendMapping {
	return &NullableApiMitreMitigation2D3fendMapping{value: val, isSet: true}
}

func (v NullableApiMitreMitigation2D3fendMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMitreMitigation2D3fendMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


