/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the AdvisoryXDB type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvisoryXDB{}

// AdvisoryXDB struct for AdvisoryXDB
type AdvisoryXDB struct {
	CloneSshUrl *string `json:"clone_ssh_url,omitempty"`
	DateAdded *string `json:"date_added,omitempty"`
	ExploitType *string `json:"exploit_type,omitempty"`
	XdbId *string `json:"xdb_id,omitempty"`
	XdbUrl *string `json:"xdb_url,omitempty"`
}

// NewAdvisoryXDB instantiates a new AdvisoryXDB object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvisoryXDB() *AdvisoryXDB {
	this := AdvisoryXDB{}
	return &this
}

// NewAdvisoryXDBWithDefaults instantiates a new AdvisoryXDB object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvisoryXDBWithDefaults() *AdvisoryXDB {
	this := AdvisoryXDB{}
	return &this
}

// GetCloneSshUrl returns the CloneSshUrl field value if set, zero value otherwise.
func (o *AdvisoryXDB) GetCloneSshUrl() string {
	if o == nil || IsNil(o.CloneSshUrl) {
		var ret string
		return ret
	}
	return *o.CloneSshUrl
}

// GetCloneSshUrlOk returns a tuple with the CloneSshUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryXDB) GetCloneSshUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CloneSshUrl) {
		return nil, false
	}
	return o.CloneSshUrl, true
}

// HasCloneSshUrl returns a boolean if a field has been set.
func (o *AdvisoryXDB) HasCloneSshUrl() bool {
	if o != nil && !IsNil(o.CloneSshUrl) {
		return true
	}

	return false
}

// SetCloneSshUrl gets a reference to the given string and assigns it to the CloneSshUrl field.
func (o *AdvisoryXDB) SetCloneSshUrl(v string) {
	o.CloneSshUrl = &v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *AdvisoryXDB) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryXDB) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *AdvisoryXDB) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *AdvisoryXDB) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetExploitType returns the ExploitType field value if set, zero value otherwise.
func (o *AdvisoryXDB) GetExploitType() string {
	if o == nil || IsNil(o.ExploitType) {
		var ret string
		return ret
	}
	return *o.ExploitType
}

// GetExploitTypeOk returns a tuple with the ExploitType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryXDB) GetExploitTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExploitType) {
		return nil, false
	}
	return o.ExploitType, true
}

// HasExploitType returns a boolean if a field has been set.
func (o *AdvisoryXDB) HasExploitType() bool {
	if o != nil && !IsNil(o.ExploitType) {
		return true
	}

	return false
}

// SetExploitType gets a reference to the given string and assigns it to the ExploitType field.
func (o *AdvisoryXDB) SetExploitType(v string) {
	o.ExploitType = &v
}

// GetXdbId returns the XdbId field value if set, zero value otherwise.
func (o *AdvisoryXDB) GetXdbId() string {
	if o == nil || IsNil(o.XdbId) {
		var ret string
		return ret
	}
	return *o.XdbId
}

// GetXdbIdOk returns a tuple with the XdbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryXDB) GetXdbIdOk() (*string, bool) {
	if o == nil || IsNil(o.XdbId) {
		return nil, false
	}
	return o.XdbId, true
}

// HasXdbId returns a boolean if a field has been set.
func (o *AdvisoryXDB) HasXdbId() bool {
	if o != nil && !IsNil(o.XdbId) {
		return true
	}

	return false
}

// SetXdbId gets a reference to the given string and assigns it to the XdbId field.
func (o *AdvisoryXDB) SetXdbId(v string) {
	o.XdbId = &v
}

// GetXdbUrl returns the XdbUrl field value if set, zero value otherwise.
func (o *AdvisoryXDB) GetXdbUrl() string {
	if o == nil || IsNil(o.XdbUrl) {
		var ret string
		return ret
	}
	return *o.XdbUrl
}

// GetXdbUrlOk returns a tuple with the XdbUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryXDB) GetXdbUrlOk() (*string, bool) {
	if o == nil || IsNil(o.XdbUrl) {
		return nil, false
	}
	return o.XdbUrl, true
}

// HasXdbUrl returns a boolean if a field has been set.
func (o *AdvisoryXDB) HasXdbUrl() bool {
	if o != nil && !IsNil(o.XdbUrl) {
		return true
	}

	return false
}

// SetXdbUrl gets a reference to the given string and assigns it to the XdbUrl field.
func (o *AdvisoryXDB) SetXdbUrl(v string) {
	o.XdbUrl = &v
}

func (o AdvisoryXDB) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvisoryXDB) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CloneSshUrl) {
		toSerialize["clone_ssh_url"] = o.CloneSshUrl
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.ExploitType) {
		toSerialize["exploit_type"] = o.ExploitType
	}
	if !IsNil(o.XdbId) {
		toSerialize["xdb_id"] = o.XdbId
	}
	if !IsNil(o.XdbUrl) {
		toSerialize["xdb_url"] = o.XdbUrl
	}
	return toSerialize, nil
}

type NullableAdvisoryXDB struct {
	value *AdvisoryXDB
	isSet bool
}

func (v NullableAdvisoryXDB) Get() *AdvisoryXDB {
	return v.value
}

func (v *NullableAdvisoryXDB) Set(val *AdvisoryXDB) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvisoryXDB) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvisoryXDB) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvisoryXDB(val *AdvisoryXDB) *NullableAdvisoryXDB {
	return &NullableAdvisoryXDB{value: val, isSet: true}
}

func (v NullableAdvisoryXDB) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvisoryXDB) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


