/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the AdvisorySolarWindsAdvisory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvisorySolarWindsAdvisory{}

// AdvisorySolarWindsAdvisory struct for AdvisorySolarWindsAdvisory
type AdvisorySolarWindsAdvisory struct {
	AffectedProducts *string `json:"affected_products,omitempty"`
	Cve []string `json:"cve,omitempty"`
	CvssScore *string `json:"cvss_score,omitempty"`
	DateAdded *string `json:"date_added,omitempty"`
	FixedVersion *string `json:"fixed_version,omitempty"`
	Severity *string `json:"severity,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Title *string `json:"title,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewAdvisorySolarWindsAdvisory instantiates a new AdvisorySolarWindsAdvisory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvisorySolarWindsAdvisory() *AdvisorySolarWindsAdvisory {
	this := AdvisorySolarWindsAdvisory{}
	return &this
}

// NewAdvisorySolarWindsAdvisoryWithDefaults instantiates a new AdvisorySolarWindsAdvisory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvisorySolarWindsAdvisoryWithDefaults() *AdvisorySolarWindsAdvisory {
	this := AdvisorySolarWindsAdvisory{}
	return &this
}

// GetAffectedProducts returns the AffectedProducts field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetAffectedProducts() string {
	if o == nil || IsNil(o.AffectedProducts) {
		var ret string
		return ret
	}
	return *o.AffectedProducts
}

// GetAffectedProductsOk returns a tuple with the AffectedProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetAffectedProductsOk() (*string, bool) {
	if o == nil || IsNil(o.AffectedProducts) {
		return nil, false
	}
	return o.AffectedProducts, true
}

// HasAffectedProducts returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasAffectedProducts() bool {
	if o != nil && !IsNil(o.AffectedProducts) {
		return true
	}

	return false
}

// SetAffectedProducts gets a reference to the given string and assigns it to the AffectedProducts field.
func (o *AdvisorySolarWindsAdvisory) SetAffectedProducts(v string) {
	o.AffectedProducts = &v
}

// GetCve returns the Cve field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetCve() []string {
	if o == nil || IsNil(o.Cve) {
		var ret []string
		return ret
	}
	return o.Cve
}

// GetCveOk returns a tuple with the Cve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetCveOk() ([]string, bool) {
	if o == nil || IsNil(o.Cve) {
		return nil, false
	}
	return o.Cve, true
}

// HasCve returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasCve() bool {
	if o != nil && !IsNil(o.Cve) {
		return true
	}

	return false
}

// SetCve gets a reference to the given []string and assigns it to the Cve field.
func (o *AdvisorySolarWindsAdvisory) SetCve(v []string) {
	o.Cve = v
}

// GetCvssScore returns the CvssScore field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetCvssScore() string {
	if o == nil || IsNil(o.CvssScore) {
		var ret string
		return ret
	}
	return *o.CvssScore
}

// GetCvssScoreOk returns a tuple with the CvssScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetCvssScoreOk() (*string, bool) {
	if o == nil || IsNil(o.CvssScore) {
		return nil, false
	}
	return o.CvssScore, true
}

// HasCvssScore returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasCvssScore() bool {
	if o != nil && !IsNil(o.CvssScore) {
		return true
	}

	return false
}

// SetCvssScore gets a reference to the given string and assigns it to the CvssScore field.
func (o *AdvisorySolarWindsAdvisory) SetCvssScore(v string) {
	o.CvssScore = &v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *AdvisorySolarWindsAdvisory) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetFixedVersion returns the FixedVersion field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetFixedVersion() string {
	if o == nil || IsNil(o.FixedVersion) {
		var ret string
		return ret
	}
	return *o.FixedVersion
}

// GetFixedVersionOk returns a tuple with the FixedVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetFixedVersionOk() (*string, bool) {
	if o == nil || IsNil(o.FixedVersion) {
		return nil, false
	}
	return o.FixedVersion, true
}

// HasFixedVersion returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasFixedVersion() bool {
	if o != nil && !IsNil(o.FixedVersion) {
		return true
	}

	return false
}

// SetFixedVersion gets a reference to the given string and assigns it to the FixedVersion field.
func (o *AdvisorySolarWindsAdvisory) SetFixedVersion(v string) {
	o.FixedVersion = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *AdvisorySolarWindsAdvisory) SetSeverity(v string) {
	o.Severity = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *AdvisorySolarWindsAdvisory) SetSummary(v string) {
	o.Summary = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AdvisorySolarWindsAdvisory) SetTitle(v string) {
	o.Title = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AdvisorySolarWindsAdvisory) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisorySolarWindsAdvisory) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AdvisorySolarWindsAdvisory) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AdvisorySolarWindsAdvisory) SetUrl(v string) {
	o.Url = &v
}

func (o AdvisorySolarWindsAdvisory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvisorySolarWindsAdvisory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AffectedProducts) {
		toSerialize["affected_products"] = o.AffectedProducts
	}
	if !IsNil(o.Cve) {
		toSerialize["cve"] = o.Cve
	}
	if !IsNil(o.CvssScore) {
		toSerialize["cvss_score"] = o.CvssScore
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.FixedVersion) {
		toSerialize["fixed_version"] = o.FixedVersion
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableAdvisorySolarWindsAdvisory struct {
	value *AdvisorySolarWindsAdvisory
	isSet bool
}

func (v NullableAdvisorySolarWindsAdvisory) Get() *AdvisorySolarWindsAdvisory {
	return v.value
}

func (v *NullableAdvisorySolarWindsAdvisory) Set(val *AdvisorySolarWindsAdvisory) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvisorySolarWindsAdvisory) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvisorySolarWindsAdvisory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvisorySolarWindsAdvisory(val *AdvisorySolarWindsAdvisory) *NullableAdvisorySolarWindsAdvisory {
	return &NullableAdvisorySolarWindsAdvisory{value: val, isSet: true}
}

func (v NullableAdvisorySolarWindsAdvisory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvisorySolarWindsAdvisory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


