/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the AdvisoryMicrosoftKb type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvisoryMicrosoftKb{}

// AdvisoryMicrosoftKb struct for AdvisoryMicrosoftKb
type AdvisoryMicrosoftKb struct {
	Cve *string `json:"cve,omitempty"`
	DateAdded *string `json:"date_added,omitempty"`
	Kbs []AdvisoryKb `json:"kbs,omitempty"`
	Threat *AdvisoryKbThreatDescription `json:"threat,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewAdvisoryMicrosoftKb instantiates a new AdvisoryMicrosoftKb object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvisoryMicrosoftKb() *AdvisoryMicrosoftKb {
	this := AdvisoryMicrosoftKb{}
	return &this
}

// NewAdvisoryMicrosoftKbWithDefaults instantiates a new AdvisoryMicrosoftKb object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvisoryMicrosoftKbWithDefaults() *AdvisoryMicrosoftKb {
	this := AdvisoryMicrosoftKb{}
	return &this
}

// GetCve returns the Cve field value if set, zero value otherwise.
func (o *AdvisoryMicrosoftKb) GetCve() string {
	if o == nil || IsNil(o.Cve) {
		var ret string
		return ret
	}
	return *o.Cve
}

// GetCveOk returns a tuple with the Cve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryMicrosoftKb) GetCveOk() (*string, bool) {
	if o == nil || IsNil(o.Cve) {
		return nil, false
	}
	return o.Cve, true
}

// HasCve returns a boolean if a field has been set.
func (o *AdvisoryMicrosoftKb) HasCve() bool {
	if o != nil && !IsNil(o.Cve) {
		return true
	}

	return false
}

// SetCve gets a reference to the given string and assigns it to the Cve field.
func (o *AdvisoryMicrosoftKb) SetCve(v string) {
	o.Cve = &v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *AdvisoryMicrosoftKb) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryMicrosoftKb) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *AdvisoryMicrosoftKb) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *AdvisoryMicrosoftKb) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetKbs returns the Kbs field value if set, zero value otherwise.
func (o *AdvisoryMicrosoftKb) GetKbs() []AdvisoryKb {
	if o == nil || IsNil(o.Kbs) {
		var ret []AdvisoryKb
		return ret
	}
	return o.Kbs
}

// GetKbsOk returns a tuple with the Kbs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryMicrosoftKb) GetKbsOk() ([]AdvisoryKb, bool) {
	if o == nil || IsNil(o.Kbs) {
		return nil, false
	}
	return o.Kbs, true
}

// HasKbs returns a boolean if a field has been set.
func (o *AdvisoryMicrosoftKb) HasKbs() bool {
	if o != nil && !IsNil(o.Kbs) {
		return true
	}

	return false
}

// SetKbs gets a reference to the given []AdvisoryKb and assigns it to the Kbs field.
func (o *AdvisoryMicrosoftKb) SetKbs(v []AdvisoryKb) {
	o.Kbs = v
}

// GetThreat returns the Threat field value if set, zero value otherwise.
func (o *AdvisoryMicrosoftKb) GetThreat() AdvisoryKbThreatDescription {
	if o == nil || IsNil(o.Threat) {
		var ret AdvisoryKbThreatDescription
		return ret
	}
	return *o.Threat
}

// GetThreatOk returns a tuple with the Threat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryMicrosoftKb) GetThreatOk() (*AdvisoryKbThreatDescription, bool) {
	if o == nil || IsNil(o.Threat) {
		return nil, false
	}
	return o.Threat, true
}

// HasThreat returns a boolean if a field has been set.
func (o *AdvisoryMicrosoftKb) HasThreat() bool {
	if o != nil && !IsNil(o.Threat) {
		return true
	}

	return false
}

// SetThreat gets a reference to the given AdvisoryKbThreatDescription and assigns it to the Threat field.
func (o *AdvisoryMicrosoftKb) SetThreat(v AdvisoryKbThreatDescription) {
	o.Threat = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AdvisoryMicrosoftKb) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryMicrosoftKb) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AdvisoryMicrosoftKb) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AdvisoryMicrosoftKb) SetTitle(v string) {
	o.Title = &v
}

func (o AdvisoryMicrosoftKb) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvisoryMicrosoftKb) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cve) {
		toSerialize["cve"] = o.Cve
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.Kbs) {
		toSerialize["kbs"] = o.Kbs
	}
	if !IsNil(o.Threat) {
		toSerialize["threat"] = o.Threat
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableAdvisoryMicrosoftKb struct {
	value *AdvisoryMicrosoftKb
	isSet bool
}

func (v NullableAdvisoryMicrosoftKb) Get() *AdvisoryMicrosoftKb {
	return v.value
}

func (v *NullableAdvisoryMicrosoftKb) Set(val *AdvisoryMicrosoftKb) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvisoryMicrosoftKb) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvisoryMicrosoftKb) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvisoryMicrosoftKb(val *AdvisoryMicrosoftKb) *NullableAdvisoryMicrosoftKb {
	return &NullableAdvisoryMicrosoftKb{value: val, isSet: true}
}

func (v NullableAdvisoryMicrosoftKb) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvisoryMicrosoftKb) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


