/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the AdvisoryTheMissingLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvisoryTheMissingLink{}

// AdvisoryTheMissingLink struct for AdvisoryTheMissingLink
type AdvisoryTheMissingLink struct {
	AffectedVersions *string `json:"affected_versions,omitempty"`
	Cve []string `json:"cve,omitempty"`
	DateAdded *string `json:"date_added,omitempty"`
	FixedVersions *string `json:"fixed_versions,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Title *string `json:"title,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewAdvisoryTheMissingLink instantiates a new AdvisoryTheMissingLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvisoryTheMissingLink() *AdvisoryTheMissingLink {
	this := AdvisoryTheMissingLink{}
	return &this
}

// NewAdvisoryTheMissingLinkWithDefaults instantiates a new AdvisoryTheMissingLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvisoryTheMissingLinkWithDefaults() *AdvisoryTheMissingLink {
	this := AdvisoryTheMissingLink{}
	return &this
}

// GetAffectedVersions returns the AffectedVersions field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetAffectedVersions() string {
	if o == nil || IsNil(o.AffectedVersions) {
		var ret string
		return ret
	}
	return *o.AffectedVersions
}

// GetAffectedVersionsOk returns a tuple with the AffectedVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetAffectedVersionsOk() (*string, bool) {
	if o == nil || IsNil(o.AffectedVersions) {
		return nil, false
	}
	return o.AffectedVersions, true
}

// HasAffectedVersions returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasAffectedVersions() bool {
	if o != nil && !IsNil(o.AffectedVersions) {
		return true
	}

	return false
}

// SetAffectedVersions gets a reference to the given string and assigns it to the AffectedVersions field.
func (o *AdvisoryTheMissingLink) SetAffectedVersions(v string) {
	o.AffectedVersions = &v
}

// GetCve returns the Cve field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetCve() []string {
	if o == nil || IsNil(o.Cve) {
		var ret []string
		return ret
	}
	return o.Cve
}

// GetCveOk returns a tuple with the Cve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetCveOk() ([]string, bool) {
	if o == nil || IsNil(o.Cve) {
		return nil, false
	}
	return o.Cve, true
}

// HasCve returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasCve() bool {
	if o != nil && !IsNil(o.Cve) {
		return true
	}

	return false
}

// SetCve gets a reference to the given []string and assigns it to the Cve field.
func (o *AdvisoryTheMissingLink) SetCve(v []string) {
	o.Cve = v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *AdvisoryTheMissingLink) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetFixedVersions returns the FixedVersions field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetFixedVersions() string {
	if o == nil || IsNil(o.FixedVersions) {
		var ret string
		return ret
	}
	return *o.FixedVersions
}

// GetFixedVersionsOk returns a tuple with the FixedVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetFixedVersionsOk() (*string, bool) {
	if o == nil || IsNil(o.FixedVersions) {
		return nil, false
	}
	return o.FixedVersions, true
}

// HasFixedVersions returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasFixedVersions() bool {
	if o != nil && !IsNil(o.FixedVersions) {
		return true
	}

	return false
}

// SetFixedVersions gets a reference to the given string and assigns it to the FixedVersions field.
func (o *AdvisoryTheMissingLink) SetFixedVersions(v string) {
	o.FixedVersions = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *AdvisoryTheMissingLink) SetSummary(v string) {
	o.Summary = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AdvisoryTheMissingLink) SetTitle(v string) {
	o.Title = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AdvisoryTheMissingLink) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryTheMissingLink) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AdvisoryTheMissingLink) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AdvisoryTheMissingLink) SetUrl(v string) {
	o.Url = &v
}

func (o AdvisoryTheMissingLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvisoryTheMissingLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AffectedVersions) {
		toSerialize["affected_versions"] = o.AffectedVersions
	}
	if !IsNil(o.Cve) {
		toSerialize["cve"] = o.Cve
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.FixedVersions) {
		toSerialize["fixed_versions"] = o.FixedVersions
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableAdvisoryTheMissingLink struct {
	value *AdvisoryTheMissingLink
	isSet bool
}

func (v NullableAdvisoryTheMissingLink) Get() *AdvisoryTheMissingLink {
	return v.value
}

func (v *NullableAdvisoryTheMissingLink) Set(val *AdvisoryTheMissingLink) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvisoryTheMissingLink) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvisoryTheMissingLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvisoryTheMissingLink(val *AdvisoryTheMissingLink) *NullableAdvisoryTheMissingLink {
	return &NullableAdvisoryTheMissingLink{value: val, isSet: true}
}

func (v NullableAdvisoryTheMissingLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvisoryTheMissingLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


