/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the ParamsIndexBackup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParamsIndexBackup{}

// ParamsIndexBackup struct for ParamsIndexBackup
type ParamsIndexBackup struct {
	DateAdded *string `json:"date_added,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Sha256 *string `json:"sha256,omitempty"`
	Url *string `json:"url,omitempty"`
	UrlApSoutheast2 *string `json:"url_ap-southeast-2,omitempty"`
	UrlEuWest2 *string `json:"url_eu-west-2,omitempty"`
	UrlExpires *string `json:"url_expires,omitempty"`
	UrlMrap *string `json:"url_mrap,omitempty"`
	UrlTtlMinutes *int32 `json:"url_ttl_minutes,omitempty"`
	UrlUsEast1 *string `json:"url_us-east-1,omitempty"`
	UrlUsWest2 *string `json:"url_us-west-2,omitempty"`
}

// NewParamsIndexBackup instantiates a new ParamsIndexBackup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParamsIndexBackup() *ParamsIndexBackup {
	this := ParamsIndexBackup{}
	return &this
}

// NewParamsIndexBackupWithDefaults instantiates a new ParamsIndexBackup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParamsIndexBackupWithDefaults() *ParamsIndexBackup {
	this := ParamsIndexBackup{}
	return &this
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *ParamsIndexBackup) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *ParamsIndexBackup) SetFilename(v string) {
	o.Filename = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *ParamsIndexBackup) SetSha256(v string) {
	o.Sha256 = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ParamsIndexBackup) SetUrl(v string) {
	o.Url = &v
}

// GetUrlApSoutheast2 returns the UrlApSoutheast2 field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlApSoutheast2() string {
	if o == nil || IsNil(o.UrlApSoutheast2) {
		var ret string
		return ret
	}
	return *o.UrlApSoutheast2
}

// GetUrlApSoutheast2Ok returns a tuple with the UrlApSoutheast2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlApSoutheast2Ok() (*string, bool) {
	if o == nil || IsNil(o.UrlApSoutheast2) {
		return nil, false
	}
	return o.UrlApSoutheast2, true
}

// HasUrlApSoutheast2 returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlApSoutheast2() bool {
	if o != nil && !IsNil(o.UrlApSoutheast2) {
		return true
	}

	return false
}

// SetUrlApSoutheast2 gets a reference to the given string and assigns it to the UrlApSoutheast2 field.
func (o *ParamsIndexBackup) SetUrlApSoutheast2(v string) {
	o.UrlApSoutheast2 = &v
}

// GetUrlEuWest2 returns the UrlEuWest2 field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlEuWest2() string {
	if o == nil || IsNil(o.UrlEuWest2) {
		var ret string
		return ret
	}
	return *o.UrlEuWest2
}

// GetUrlEuWest2Ok returns a tuple with the UrlEuWest2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlEuWest2Ok() (*string, bool) {
	if o == nil || IsNil(o.UrlEuWest2) {
		return nil, false
	}
	return o.UrlEuWest2, true
}

// HasUrlEuWest2 returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlEuWest2() bool {
	if o != nil && !IsNil(o.UrlEuWest2) {
		return true
	}

	return false
}

// SetUrlEuWest2 gets a reference to the given string and assigns it to the UrlEuWest2 field.
func (o *ParamsIndexBackup) SetUrlEuWest2(v string) {
	o.UrlEuWest2 = &v
}

// GetUrlExpires returns the UrlExpires field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlExpires() string {
	if o == nil || IsNil(o.UrlExpires) {
		var ret string
		return ret
	}
	return *o.UrlExpires
}

// GetUrlExpiresOk returns a tuple with the UrlExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.UrlExpires) {
		return nil, false
	}
	return o.UrlExpires, true
}

// HasUrlExpires returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlExpires() bool {
	if o != nil && !IsNil(o.UrlExpires) {
		return true
	}

	return false
}

// SetUrlExpires gets a reference to the given string and assigns it to the UrlExpires field.
func (o *ParamsIndexBackup) SetUrlExpires(v string) {
	o.UrlExpires = &v
}

// GetUrlMrap returns the UrlMrap field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlMrap() string {
	if o == nil || IsNil(o.UrlMrap) {
		var ret string
		return ret
	}
	return *o.UrlMrap
}

// GetUrlMrapOk returns a tuple with the UrlMrap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlMrapOk() (*string, bool) {
	if o == nil || IsNil(o.UrlMrap) {
		return nil, false
	}
	return o.UrlMrap, true
}

// HasUrlMrap returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlMrap() bool {
	if o != nil && !IsNil(o.UrlMrap) {
		return true
	}

	return false
}

// SetUrlMrap gets a reference to the given string and assigns it to the UrlMrap field.
func (o *ParamsIndexBackup) SetUrlMrap(v string) {
	o.UrlMrap = &v
}

// GetUrlTtlMinutes returns the UrlTtlMinutes field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlTtlMinutes() int32 {
	if o == nil || IsNil(o.UrlTtlMinutes) {
		var ret int32
		return ret
	}
	return *o.UrlTtlMinutes
}

// GetUrlTtlMinutesOk returns a tuple with the UrlTtlMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlTtlMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.UrlTtlMinutes) {
		return nil, false
	}
	return o.UrlTtlMinutes, true
}

// HasUrlTtlMinutes returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlTtlMinutes() bool {
	if o != nil && !IsNil(o.UrlTtlMinutes) {
		return true
	}

	return false
}

// SetUrlTtlMinutes gets a reference to the given int32 and assigns it to the UrlTtlMinutes field.
func (o *ParamsIndexBackup) SetUrlTtlMinutes(v int32) {
	o.UrlTtlMinutes = &v
}

// GetUrlUsEast1 returns the UrlUsEast1 field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlUsEast1() string {
	if o == nil || IsNil(o.UrlUsEast1) {
		var ret string
		return ret
	}
	return *o.UrlUsEast1
}

// GetUrlUsEast1Ok returns a tuple with the UrlUsEast1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlUsEast1Ok() (*string, bool) {
	if o == nil || IsNil(o.UrlUsEast1) {
		return nil, false
	}
	return o.UrlUsEast1, true
}

// HasUrlUsEast1 returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlUsEast1() bool {
	if o != nil && !IsNil(o.UrlUsEast1) {
		return true
	}

	return false
}

// SetUrlUsEast1 gets a reference to the given string and assigns it to the UrlUsEast1 field.
func (o *ParamsIndexBackup) SetUrlUsEast1(v string) {
	o.UrlUsEast1 = &v
}

// GetUrlUsWest2 returns the UrlUsWest2 field value if set, zero value otherwise.
func (o *ParamsIndexBackup) GetUrlUsWest2() string {
	if o == nil || IsNil(o.UrlUsWest2) {
		var ret string
		return ret
	}
	return *o.UrlUsWest2
}

// GetUrlUsWest2Ok returns a tuple with the UrlUsWest2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamsIndexBackup) GetUrlUsWest2Ok() (*string, bool) {
	if o == nil || IsNil(o.UrlUsWest2) {
		return nil, false
	}
	return o.UrlUsWest2, true
}

// HasUrlUsWest2 returns a boolean if a field has been set.
func (o *ParamsIndexBackup) HasUrlUsWest2() bool {
	if o != nil && !IsNil(o.UrlUsWest2) {
		return true
	}

	return false
}

// SetUrlUsWest2 gets a reference to the given string and assigns it to the UrlUsWest2 field.
func (o *ParamsIndexBackup) SetUrlUsWest2(v string) {
	o.UrlUsWest2 = &v
}

func (o ParamsIndexBackup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParamsIndexBackup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.UrlApSoutheast2) {
		toSerialize["url_ap-southeast-2"] = o.UrlApSoutheast2
	}
	if !IsNil(o.UrlEuWest2) {
		toSerialize["url_eu-west-2"] = o.UrlEuWest2
	}
	if !IsNil(o.UrlExpires) {
		toSerialize["url_expires"] = o.UrlExpires
	}
	if !IsNil(o.UrlMrap) {
		toSerialize["url_mrap"] = o.UrlMrap
	}
	if !IsNil(o.UrlTtlMinutes) {
		toSerialize["url_ttl_minutes"] = o.UrlTtlMinutes
	}
	if !IsNil(o.UrlUsEast1) {
		toSerialize["url_us-east-1"] = o.UrlUsEast1
	}
	if !IsNil(o.UrlUsWest2) {
		toSerialize["url_us-west-2"] = o.UrlUsWest2
	}
	return toSerialize, nil
}

type NullableParamsIndexBackup struct {
	value *ParamsIndexBackup
	isSet bool
}

func (v NullableParamsIndexBackup) Get() *ParamsIndexBackup {
	return v.value
}

func (v *NullableParamsIndexBackup) Set(val *ParamsIndexBackup) {
	v.value = val
	v.isSet = true
}

func (v NullableParamsIndexBackup) IsSet() bool {
	return v.isSet
}

func (v *NullableParamsIndexBackup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParamsIndexBackup(val *ParamsIndexBackup) *NullableParamsIndexBackup {
	return &NullableParamsIndexBackup{value: val, isSet: true}
}

func (v NullableParamsIndexBackup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParamsIndexBackup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


