/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination{}

// RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination struct for RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination
type RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination struct {
	Benchmark *float32 `json:"_benchmark,omitempty"`
	Meta *PaginatePagination `json:"_meta,omitempty"`
	Data []AdvisorySuseSecurity `json:"data,omitempty"`
}

// NewRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination instantiates a new RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination() *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination {
	this := RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination{}
	return &this
}

// NewRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePaginationWithDefaults instantiates a new RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePaginationWithDefaults() *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination {
	this := RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination{}
	return &this
}

// GetBenchmark returns the Benchmark field value if set, zero value otherwise.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) GetBenchmark() float32 {
	if o == nil || IsNil(o.Benchmark) {
		var ret float32
		return ret
	}
	return *o.Benchmark
}

// GetBenchmarkOk returns a tuple with the Benchmark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) GetBenchmarkOk() (*float32, bool) {
	if o == nil || IsNil(o.Benchmark) {
		return nil, false
	}
	return o.Benchmark, true
}

// HasBenchmark returns a boolean if a field has been set.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) HasBenchmark() bool {
	if o != nil && !IsNil(o.Benchmark) {
		return true
	}

	return false
}

// SetBenchmark gets a reference to the given float32 and assigns it to the Benchmark field.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) SetBenchmark(v float32) {
	o.Benchmark = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) GetMeta() PaginatePagination {
	if o == nil || IsNil(o.Meta) {
		var ret PaginatePagination
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) GetMetaOk() (*PaginatePagination, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginatePagination and assigns it to the Meta field.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) SetMeta(v PaginatePagination) {
	o.Meta = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) GetData() []AdvisorySuseSecurity {
	if o == nil || IsNil(o.Data) {
		var ret []AdvisorySuseSecurity
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) GetDataOk() ([]AdvisorySuseSecurity, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AdvisorySuseSecurity and assigns it to the Data field.
func (o *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) SetData(v []AdvisorySuseSecurity) {
	o.Data = v
}

func (o RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Benchmark) {
		toSerialize["_benchmark"] = o.Benchmark
	}
	if !IsNil(o.Meta) {
		toSerialize["_meta"] = o.Meta
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination struct {
	value *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination
	isSet bool
}

func (v NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) Get() *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination {
	return v.value
}

func (v *NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) Set(val *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination(val *RenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) *NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination {
	return &NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination{value: val, isSet: true}
}

func (v NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderResponseWithMetadataArrayAdvisorySuseSecurityPaginatePagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


