/*
VulnCheck API

Version 3 of the VulnCheck API

API version: 3.0
Contact: support@vulncheck.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vulncheck

import (
	"encoding/json"
)

// checks if the AdvisoryJVNAdvisoryItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvisoryJVNAdvisoryItem{}

// AdvisoryJVNAdvisoryItem struct for AdvisoryJVNAdvisoryItem
type AdvisoryJVNAdvisoryItem struct {
	Cpe []AdvisoryJVNCPE `json:"cpe,omitempty"`
	Cve []string `json:"cve,omitempty"`
	Cvss []AdvisoryCVSS `json:"cvss,omitempty"`
	DateAdded *string `json:"date_added,omitempty"`
	Description *string `json:"description,omitempty"`
	DescriptionEn *string `json:"description_en,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	Issued *string `json:"issued,omitempty"`
	Modified *string `json:"modified,omitempty"`
	References []AdvisoryJVNReference `json:"references,omitempty"`
	Title *string `json:"title,omitempty"`
	TitleEn *string `json:"title_en,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Url *string `json:"url,omitempty"`
	UrlEn *string `json:"url_en,omitempty"`
}

// NewAdvisoryJVNAdvisoryItem instantiates a new AdvisoryJVNAdvisoryItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvisoryJVNAdvisoryItem() *AdvisoryJVNAdvisoryItem {
	this := AdvisoryJVNAdvisoryItem{}
	return &this
}

// NewAdvisoryJVNAdvisoryItemWithDefaults instantiates a new AdvisoryJVNAdvisoryItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvisoryJVNAdvisoryItemWithDefaults() *AdvisoryJVNAdvisoryItem {
	this := AdvisoryJVNAdvisoryItem{}
	return &this
}

// GetCpe returns the Cpe field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetCpe() []AdvisoryJVNCPE {
	if o == nil || IsNil(o.Cpe) {
		var ret []AdvisoryJVNCPE
		return ret
	}
	return o.Cpe
}

// GetCpeOk returns a tuple with the Cpe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetCpeOk() ([]AdvisoryJVNCPE, bool) {
	if o == nil || IsNil(o.Cpe) {
		return nil, false
	}
	return o.Cpe, true
}

// HasCpe returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasCpe() bool {
	if o != nil && !IsNil(o.Cpe) {
		return true
	}

	return false
}

// SetCpe gets a reference to the given []AdvisoryJVNCPE and assigns it to the Cpe field.
func (o *AdvisoryJVNAdvisoryItem) SetCpe(v []AdvisoryJVNCPE) {
	o.Cpe = v
}

// GetCve returns the Cve field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetCve() []string {
	if o == nil || IsNil(o.Cve) {
		var ret []string
		return ret
	}
	return o.Cve
}

// GetCveOk returns a tuple with the Cve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetCveOk() ([]string, bool) {
	if o == nil || IsNil(o.Cve) {
		return nil, false
	}
	return o.Cve, true
}

// HasCve returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasCve() bool {
	if o != nil && !IsNil(o.Cve) {
		return true
	}

	return false
}

// SetCve gets a reference to the given []string and assigns it to the Cve field.
func (o *AdvisoryJVNAdvisoryItem) SetCve(v []string) {
	o.Cve = v
}

// GetCvss returns the Cvss field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetCvss() []AdvisoryCVSS {
	if o == nil || IsNil(o.Cvss) {
		var ret []AdvisoryCVSS
		return ret
	}
	return o.Cvss
}

// GetCvssOk returns a tuple with the Cvss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetCvssOk() ([]AdvisoryCVSS, bool) {
	if o == nil || IsNil(o.Cvss) {
		return nil, false
	}
	return o.Cvss, true
}

// HasCvss returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasCvss() bool {
	if o != nil && !IsNil(o.Cvss) {
		return true
	}

	return false
}

// SetCvss gets a reference to the given []AdvisoryCVSS and assigns it to the Cvss field.
func (o *AdvisoryJVNAdvisoryItem) SetCvss(v []AdvisoryCVSS) {
	o.Cvss = v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *AdvisoryJVNAdvisoryItem) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AdvisoryJVNAdvisoryItem) SetDescription(v string) {
	o.Description = &v
}

// GetDescriptionEn returns the DescriptionEn field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetDescriptionEn() string {
	if o == nil || IsNil(o.DescriptionEn) {
		var ret string
		return ret
	}
	return *o.DescriptionEn
}

// GetDescriptionEnOk returns a tuple with the DescriptionEn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetDescriptionEnOk() (*string, bool) {
	if o == nil || IsNil(o.DescriptionEn) {
		return nil, false
	}
	return o.DescriptionEn, true
}

// HasDescriptionEn returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasDescriptionEn() bool {
	if o != nil && !IsNil(o.DescriptionEn) {
		return true
	}

	return false
}

// SetDescriptionEn gets a reference to the given string and assigns it to the DescriptionEn field.
func (o *AdvisoryJVNAdvisoryItem) SetDescriptionEn(v string) {
	o.DescriptionEn = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *AdvisoryJVNAdvisoryItem) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetIssued returns the Issued field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetIssued() string {
	if o == nil || IsNil(o.Issued) {
		var ret string
		return ret
	}
	return *o.Issued
}

// GetIssuedOk returns a tuple with the Issued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetIssuedOk() (*string, bool) {
	if o == nil || IsNil(o.Issued) {
		return nil, false
	}
	return o.Issued, true
}

// HasIssued returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasIssued() bool {
	if o != nil && !IsNil(o.Issued) {
		return true
	}

	return false
}

// SetIssued gets a reference to the given string and assigns it to the Issued field.
func (o *AdvisoryJVNAdvisoryItem) SetIssued(v string) {
	o.Issued = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetModified() string {
	if o == nil || IsNil(o.Modified) {
		var ret string
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given string and assigns it to the Modified field.
func (o *AdvisoryJVNAdvisoryItem) SetModified(v string) {
	o.Modified = &v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetReferences() []AdvisoryJVNReference {
	if o == nil || IsNil(o.References) {
		var ret []AdvisoryJVNReference
		return ret
	}
	return o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetReferencesOk() ([]AdvisoryJVNReference, bool) {
	if o == nil || IsNil(o.References) {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasReferences() bool {
	if o != nil && !IsNil(o.References) {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []AdvisoryJVNReference and assigns it to the References field.
func (o *AdvisoryJVNAdvisoryItem) SetReferences(v []AdvisoryJVNReference) {
	o.References = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AdvisoryJVNAdvisoryItem) SetTitle(v string) {
	o.Title = &v
}

// GetTitleEn returns the TitleEn field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetTitleEn() string {
	if o == nil || IsNil(o.TitleEn) {
		var ret string
		return ret
	}
	return *o.TitleEn
}

// GetTitleEnOk returns a tuple with the TitleEn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetTitleEnOk() (*string, bool) {
	if o == nil || IsNil(o.TitleEn) {
		return nil, false
	}
	return o.TitleEn, true
}

// HasTitleEn returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasTitleEn() bool {
	if o != nil && !IsNil(o.TitleEn) {
		return true
	}

	return false
}

// SetTitleEn gets a reference to the given string and assigns it to the TitleEn field.
func (o *AdvisoryJVNAdvisoryItem) SetTitleEn(v string) {
	o.TitleEn = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *AdvisoryJVNAdvisoryItem) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AdvisoryJVNAdvisoryItem) SetUrl(v string) {
	o.Url = &v
}

// GetUrlEn returns the UrlEn field value if set, zero value otherwise.
func (o *AdvisoryJVNAdvisoryItem) GetUrlEn() string {
	if o == nil || IsNil(o.UrlEn) {
		var ret string
		return ret
	}
	return *o.UrlEn
}

// GetUrlEnOk returns a tuple with the UrlEn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvisoryJVNAdvisoryItem) GetUrlEnOk() (*string, bool) {
	if o == nil || IsNil(o.UrlEn) {
		return nil, false
	}
	return o.UrlEn, true
}

// HasUrlEn returns a boolean if a field has been set.
func (o *AdvisoryJVNAdvisoryItem) HasUrlEn() bool {
	if o != nil && !IsNil(o.UrlEn) {
		return true
	}

	return false
}

// SetUrlEn gets a reference to the given string and assigns it to the UrlEn field.
func (o *AdvisoryJVNAdvisoryItem) SetUrlEn(v string) {
	o.UrlEn = &v
}

func (o AdvisoryJVNAdvisoryItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvisoryJVNAdvisoryItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpe) {
		toSerialize["cpe"] = o.Cpe
	}
	if !IsNil(o.Cve) {
		toSerialize["cve"] = o.Cve
	}
	if !IsNil(o.Cvss) {
		toSerialize["cvss"] = o.Cvss
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DescriptionEn) {
		toSerialize["description_en"] = o.DescriptionEn
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.Issued) {
		toSerialize["issued"] = o.Issued
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.References) {
		toSerialize["references"] = o.References
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.TitleEn) {
		toSerialize["title_en"] = o.TitleEn
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.UrlEn) {
		toSerialize["url_en"] = o.UrlEn
	}
	return toSerialize, nil
}

type NullableAdvisoryJVNAdvisoryItem struct {
	value *AdvisoryJVNAdvisoryItem
	isSet bool
}

func (v NullableAdvisoryJVNAdvisoryItem) Get() *AdvisoryJVNAdvisoryItem {
	return v.value
}

func (v *NullableAdvisoryJVNAdvisoryItem) Set(val *AdvisoryJVNAdvisoryItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvisoryJVNAdvisoryItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvisoryJVNAdvisoryItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvisoryJVNAdvisoryItem(val *AdvisoryJVNAdvisoryItem) *NullableAdvisoryJVNAdvisoryItem {
	return &NullableAdvisoryJVNAdvisoryItem{value: val, isSet: true}
}

func (v NullableAdvisoryJVNAdvisoryItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvisoryJVNAdvisoryItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


