---
name: CI 🧪

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: Test
        working-directory: tests
        env:
          VULNCHECK_API_TOKEN: ${{ secrets.VULNCHECK_TOKEN }}
        run: go test integration_test.go
