---
name: Create Release 🚀

on:
  push:
    branches:
      - main
    paths:
      - vulncheck/go.mod
      - vulncheck/go.sum
      - vulncheck/*.go

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app-id: ${{ secrets.VULNCHECK_GITHUB_RELEASE_APP_ID }}
          private-key: ${{ secrets.VULNCHECK_GITHUB_RELEASE_APP_KEY }}

      - name: Check out HEAD ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          path: head
          fetch-tags: true
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
          cache-dependency-path: head/tests/go.sum

      - name: Tests
        working-directory: head/tests
        env:
          VULNCHECK_API_TOKEN: ${{ secrets.VULNCHECK_TOKEN }}
        run: go test integration_test.go

      - name: Get versions
        id: versions
        working-directory: head
        run: |
          CURRENT_VERSION=$(yq e '.additionalProperties.packageVersion' go-generator-config.yaml)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "All available tags:"
          git tag -l
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          if [ -z "$LATEST_TAG" ]; then
            echo "No valid version tags found"
            exit 1
          fi
          echo "Found latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Check out previous release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: previous
          ref: ${{ steps.versions.outputs.latest_tag }}
          fetch-tags: true

      - name: Make temp openapi-diff file
        run: touch ${{ github.workspace }}/head/openapi-diff.md
      - name: Run openapi-diff
        uses: docker://openapitools/openapi-diff:latest
        with:
          args: head/openapi.json previous/openapi.json --markdown head/openapi-diff.md

      - name: Check if tag exists
        id: check_tag
        working-directory: head
        run: |
          if git ls-remote --exit-code --tags origin "refs/tags/v${{ steps.versions.outputs.current_version }}"; then
            echo "Tag v${{ steps.versions.outputs.current_version }} already exists, skipping release"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        working-directory: head
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          git tag -f v${{ steps.versions.outputs.current_version }}
          git push --force origin v${{ steps.versions.outputs.current_version }}

      - name: Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/head/openapi-diff.md
          tag_name: v${{ steps.versions.outputs.current_version }}
          token: ${{ steps.generate_token.outputs.token }}
